### ISSUE TITLE
Add scroll

### ISSUE THREAD

**Issue by alonsomaniaco** [tjaart/plasma-drydock#6]
When you have lots of docker containers in your machine some of then are not be showed because of the size of the monitor. It would be so great to have a scroll to see all containers in the system.

![](https://i.imgur.com/YTXKiZv.png)

**Comment by tjaart** [comment]
Please see if this new version works for you: 

https://github.com/tjaart/plasma-drydock/releases/tag/v1.1

**Comment by alonsomaniaco** [comment]
Hi @tjaart. First of all thanks for your effort and work on this plasmoid!
I have tried this new version that you mention but unfortunately I don't see any scroll in the component. I saw you have added a scroll component. I am completely new on qml working and plasma components but maybe there is some config or parameter that you miss in the scroll component?
Let me know if I can help on anything.

Thanks!

**Comment by tjaart** [comment]
@alonsomaniaco I am more or less in the same boat (I am a c# dev by trade). I am fairly sure the scroll works, I am using Kde neon user edition latest. Plasma is very stubborn with caching of widgets, when I upgrade the widget on my system I always have to kill and restart plasmashell. 

You are welcome to help if you like! You can clone the repo and the `run.sh` command in the root should start the widget in `plasmoidviewer`. If you run `upgrade.sh` it should upgrade your local widget, then you can just kill and start plasmashell again.

**Comment by tjaart** [comment]
Please let me know if it's still an issue. I will close for now.

**Comment by alonsomaniaco** [comment]
Hi @tjaart I have been busy today. I will recheck it tomorrow and comment here the results of it.
Thanks anyway for the effort!!
I have forked the repo to try to help to improve it. I will try to send pr!
