### ISSUE TITLE
There is a way to show container name rather than image name?

### ISSUE THREAD

**Issue by ivanseibel** [tjaart/plasma-drydock#7]
In some cases I have 2 or 3 equal images to different objectives and I distinguish them by its names. Can I do some type of configuration to get repository names, or it will demands code implementation?

**Comment by tjaart** [comment]
Hi, yes this requires a code change, but specifically relates to #3

**Comment by ivanseibel** [comment]
Oh sorry! I didn't see that there is already a problem with that ... I'm going to close. Thanks for the quick response ;)

**Comment by tjaart** [comment]
No worries @ivanseibel . I started working on this last night but ran out of time. It's fairly straightforward but I would like to make it possible to pick either the container name or the image name. You can subscribe to the other issue if you like, and you will see when it's updated. 

Also out of curiosity, how did you install it? Are you using the kde store/ ghns or installing it from this repo?

**Comment by ivanseibel** [comment]
I'm happy with your news, I'm already subscribed that issue. 

Installation was through store, but I believe have no difficult to install by cloning the repository.
