### ISSUE TITLE
module "QtQuick.Controls "version 2.14 is not installed

### ISSUE THREAD

**Issue by ivanseibel** [tjaart/plasma-drydock#9]
Hello my friend!

I tried to install today by cloning the repository and running ./install_local.sh.

The installation went smoothly, but when I click on the widget, the message about QtQuick.Controls is displayed.

What I tried to do to solve:
- Widget folder was removed from my local user folder to recreate from scratch from new installation.
- Session was restarted.

If I'm not wrong, this library was provided by qml-module-qtquick-control ..., which is in version 5.12.8-0ubuntu2 on my system.

Any clues?

Full error message:
There was an error loading the QML file: file: `///home/ivan/.local/share/plasma/plasmoids/org.kde.drydock/contents/ui/main.qml:`
`20: 1: module "QtQuick.Controls "version 2.14 is not installed`

**Comment by tjaart** [comment]
Which version of qt and  KDE are you using?

**Comment by alonsomaniaco** [comment]
Hi @tjaart now I am facing this same problem when I tried to install the new version that you mentioned in #6.

My versions are:
Operating System: Fedora 32
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.13.2
Kernel Version: 5.6.13-300.fc32.x86_64
OS Type: 64-bit
Processors: 4 × AMD A8-3870 APU with Radeon(tm) HD Graphics
Memory: 7,7 GiB

I will try to investigate the error to try to solve it or let me know if you face any solution.

Thanks!

**Comment by alonsomaniaco** [comment]
I have found that if you change version of QtQuick.Controls from 2.14 to 2.12 the plasma is working again and now I see the scrollbar that you added in #6. 
Please @tjaart check my PR and say me if there is another way to do it or if it is correct.
Thanks!

**Comment by tjaart** [comment]
Looks good. I will do another release and then close this issue. 

@ivanseibel I hope this fix will work for you as well.

**Comment by tjaart** [comment]
It should work now in the latest release. 

I'm going to close this issue for now, please feel free to do more prs or suggestions. Unfortunately I can't test older versions of Qt. 


###A link to the release:
https://github.com/tjaart/plasma-drydock/releases/tag/v1.2.1

If the widget is working now and you are happy with it will you please take a moment to rate it on the KDE store. 

https://store.kde.org/p/1369390/

**Comment by alonsomaniaco** [comment]
Hi @tjaart works perfect for me! :muscle:

**Comment by ivanseibel** [comment]
Now it's working like a charm! :1st_place_medal:
